### ISSUE TITLE
Async read of FileInfo

### ISSUE THREAD

**Issue by tipa** [RRSantos/fontInfo#1]
Great small library - *exactly* what I was looking for. Thanks so much for making it available on NuGet!
One small suggestion: I am using this in a UWP app. The current constructor takes a file path and uses a blocking/non-async IO calls to open the stream, which is not ideal when called from a UI thread. So an async-version would be great :)

**Comment by RRSantos** [comment]
Hey @tipa ! Thanks for the feedback and for using the library.
I've just changed the library to work async and published a new NuGet package (v1.0.0)

**Comment by tipa** [comment]
@RRSantos Oh wow, thanks a lot!

One small improvement that could be made for performance nerds like me is using [ConfigureAwait(false)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.configureawait?view=net-5.0) to the async method calls. It is [recommended to use in libraries](https://devblogs.microsoft.com/dotnet/configureawait-faq/#when-should-i-use-configureawaitfalse).
If you want, I can try to make a pull request for that change

**Comment by RRSantos** [comment]
@tipa thanks again for the feedback. 
Sure. I 'd love to receive a PR with this enhancement :)

**Comment by tipa** [comment]
Done :)

**Comment by RRSantos** [comment]
Nice! Version 1.0.1 published on nuget.org
